version: '3.9'

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: kalbase
      POSTGRES_PASSWORD: passpasswpossword
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - 5432:5432

volumes:
  db-data:
